local:
  adapter: postgresql
  host: <%= ENV['DB_SERVER'] %>
  database: <%= ENV['DB_DATABASE'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  username: <%= ENV['DB_USERNAME'] %>
  port: <%= ENV['DB_PORT'] %>
  reconnect: true


development:
  adapter: postgresql
  host: <%= ENV['DB_SERVER'] %>
  database: <%= ENV['DB_DATABASE'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  username: <%= ENV['DB_USERNAME'] %>
  port: <%= ENV['DB_PORT'] %>
  pool: 3
  reconnect: true